config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :users do
    resource :relationships, only:[:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  root to: "homes#top"
  get 'home/about', to: "homes#about"

  get 'search', to: 'searches#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}

  #本の検索メソッド
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?", "#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?", "#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?", "%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?", "%#{word}%")
    else
      @book = Book.all
    end
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy

  has_many :favorites, dependent: :destroy

  has_many :book_comments, dependent: :destroy

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, length: {in: 2..20}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end

  # フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  #フォローを解除したときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  #フォローしているのかどうかの処理
  def following?(user)
    followings.include?(user)
  end

  #ユーザーの検索メソッド
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?", "#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?", "%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    if @comment.save
      flash[:notice] = "You have created comment successfully."
    else
      render 'books/show'
    end
  end

  def destroy
    BookComment.find(params[:id]).destroy
    flash.now[:alert] = '投稿を削除しました'
    @book = Book.find(params[:book_id])
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @book_new = Book.new
    @comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
    unless @book.user == current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    @book = favorite.book
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  #フォローするとき
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  #フォローを解除するとき
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  #フォロー一覧
  def followings
    user = User.find(params[:user_id])
    @follows = user.followings
  end

  #フォロワー一覧
  def followers
    user = User.find(params[:user_id])
    @followers = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]
    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @books = Book.looks(params[:search], params[:word])
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  def index
    @book = Book.new
    @users = User.all
  end

  def show
    @book = Book.new
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comments.html.erb
<% book.book_comments.each do |book_comment| %>
  <tr>
    <td>
      <%= link_to user_path(book.user) do %>
        <%= image_tag book_comment.user.get_profile_image(100,100) %><br>
        <%= book_comment.user.name %>
      <% end %>
    </td>
    <td><%= book_comment.comment %></td>
    <td>
      <% if book_comment.user == current_user %>
        <%= link_to "Destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, remote: true, class: 'btn btn-danger', data: { confirm: "削除してもよろしいですか？" } %>
      <% end %>
    </td>
  </tr>
<% end %>

app/views/book_comments/_form.html.erb
<%= form_with model: [book, comment], local: false do |f| %>
  <%= f.text_area :comment %>
  <%= f.submit "送信" %>
<% end %>

app/views/book_comments/create.js.erb
$('textarea').val('')
$('.comments-counts').html("<%= j(render 'books/detail', book: @book) %>")
$('.comments-index').html("<%= j(render 'book_comments/comments', book: @book ) %>")

app/views/book_comments/destroy.js.erb
$('textarea').val('')
$('.comments-counts').html("<%= j(render 'books/detail', book: @book) %>")
$('.comments-index').html("<%= j(render 'book_comments/comments', book: @book ) %>")

app/views/books/_detail.html.erb
<h2>Book detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
                <%= image_tag book.user.get_profile_image(80,80) %><br/>
                <%= book.user.name %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book) %></td>
            <td><%= book.body %></td>
            <% if current_user == book.user %>
              <td><%= link_to "Edit", edit_book_path(book), class: 'btn btn-success' %></td>
              <td><%= link_to "Destroy", book_path(book), method: :delete, class: 'btn btn-danger', data: { confirm: "削除してもよろしいですか？" } %></td>
            <% end %>
            <td id="favorite-buttons-<%= book.id %>">
              <%= render 'favorites/favorite', book: book %>
            </td>
            <td class="comments-counts">コメント数:<%= book.book_comments.count %></td>
          </tr>
        </tbody>
      </table>

app/views/books/_form.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book , local: true do |f| %>
  <div class="form-group">
    <label for="book_title">Title</label><br/>
    <%= f.text_field :title %>
  </div>

  <div class="form-group">
    <label for="book_opinion">Opinion</label><br/>
    <%= f.text_field :body %>
  </div>

  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success' %>
  </div>


<% end %>

app/views/books/_index.html.erb
  <h2>Books</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th></th>
        <th>Title</th>
        <th>Opinion</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to user_path(book.user) do %>
            <%= image_tag book.user.get_profile_image(80,80) %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= book.body %></td>
        <td id="favorite-buttons-<%= book.id %>">
          <%= render 'favorites/favorite', book: book %>
        </td>
        <td>コメント数:<%= book.book_comments.count %></td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class="container">
  <%= render 'layouts/error', obj: @book %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

  		<%= form_with model: @book , local: true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label><br/>
        <%= f.text_field :title %>
      </div>

      <div class="form-group">
        <label for="book_opinion">Opinion</label><br/>
        <%= f.text_field :body %>
      </div>

      <div class="form-group">
        <%= f.submit 'Update Book', class: 'btn btn-success' %>
      </div>

      <%= link_to "Show", book_path(@book) %>|<%= link_to "Back", books_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/error', obj: @book %>
  <div class="row">

    <div class="col-md-3">
      <!--userinfo部分-->
      <%= render 'users/userinfo', user: current_user %>
      <!--新規投稿フォーム-->
      <%= render 'form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <!--本の一覧部分-->
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--userinfo部分-->
      <%= render 'users/userinfo', user: @book.user %>
      <!--新規投稿フォーム-->
      <%= render 'form', book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <div class="comments-counts">
        <%= render 'detail', book: @book %>
      </div>

      <div>
        <table>
          <tbody>
            <div class="comments-index">
              <%= render 'book_comments/comments', book: @book %>
            </div>
          </tbody>
        </table>



      </div>
      <div class="comments-form">
        <%= render 'book_comments/form', book: @book, comment: @comment %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
  <p>
    <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
      ♥<%= book.favorites.count %> いいね
    <% end %>
  </p>
<% else %>
  <p>
    <%= link_to book_favorites_path(book), method: :post, remote: true do %>
      ♡<%= book.favorites.count %> いいね
    <% end %>
  </p>
<% end %>

app/views/favorites/create.js.erb
$('#favorite-buttons-<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/favorites/destroy.js.erb
$('#favorite-buttons-<%= @book.id %>').html("<%= j(render "favorites/favorite", book: @book) %>");

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <%= link_to "Log in", new_user_session_path, class: 'btn btn-info btn-sm btn-block mb-3 sign_in' %>
        </div>
        <div class="row">
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-success btn-sm btn-block sign_up' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/relationships/followers.html.erb
<h1>Follower Users</h1>
<% if @followers.exists? %>
  <%= render 'users/index', users: @followers %>
<% else %>
  <p>ユーザーはいません。</p>
<% end %>

app/views/relationships/followings.html.erb
<h1>Follow Users</h1>
<% if @follows.exists? %>
  <%= render 'users/index', users: @follows %>
<% else %>
  <p>ユーザーはいません。</p>
<% end %>

app/views/searches/_search.html.erb
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, method: :get do |f| %>
      <%= f.text_field :word %>
      <%= f.select :range, options_for_select([["User"], ["Book"]]) %>
      <%= f.select :search, options_for_select([["完全一致", "perfect_match"], ["前方一致", "forward_match"], ["後方一致", "backward"], ["部分一致", "partial_match"]]) %>
      <%= f.submit "検索" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<!--検索対象モデルがUserの時 -->
<% if @range == "User" %>
  <h2>Users seach for <%= params[:word] %></h2>
  <table class="table table-hover table-inverse">
    <thead>
      <td></td>
      <th>name</th>
      <th>detail</th>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.get_profile_image(100,100) %></td>
          <td><%= user.name %></td>
          <td><%= link_to "Show", user_path(user) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <!--検索対象モデルがUserではない時(= 検索対象モデルがBookの時) -->
  <h2>Books seach for <%= params[:word] %></h2>
  <table class="table table-hover table-inverse">
    <thead>
      <td></td>
      <th>Title</th>
      <th>Opinion</th>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td><%= book.user.get_profile_image(50,50) %></td>
          <td><%= book.title %></td>
          <td><%= book.body %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_index.html.erb
<h2>Users</h2>
  <table class="table table-hover table-inverse">
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% users.each do |user| %>
      <tr>
        <td>
          <%= image_tag user.get_profile_image(80,80) %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user != user %>
            <% if current_user.following?(user) %>
              <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
            <% else %>
              <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
            <% end %>
          <% end %>
        </td>
        <td>
          <%= link_to "Show", user_path(user.id) %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/users/_userinfo.html.erb
<h2>User info</h2>
<table class="table">
  <tbody>
    <tr><%= image_tag user.get_profile_image(100,100) %></tr>
    <tr>
	    <th>name</th>
	    <th><%= user.name %></th>
    </tr>
    <tr>
	    <th>introduction</th>
	    <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>follows</th>
      <th>
        <%= link_to user_followings_path(user.id) do %>
          <%= user.followings.count %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>followers</th>
      <th>
        <%= link_to user_followers_path(user.id) do %>
          <%= user.followers.count %>
        <% end %>
      </th>
    </tr>
  </tbody>
</table>

<div class="row">
  <% if current_user == user %>
    <%= link_to edit_user_path(user), class: 'btn btn-outline-secondary btn-block' do %>
      <i class="fas fa-user-cog"></i>
    <% end %>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <%= render 'layouts/error', obj: @user %>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local: true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label><br/>
        <%= f.text_field :name %>
      </div>
      <div class="form-group">
        <label for="user_image">Image</label>
        <%= f.file_field :profile_image, accept: "image/*" %><br/>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_field :introduction %>
      </div>
      <div class="form-group">
        <%= f.submit "Update User", class: 'btn btn-secondary' %>
      </div>
    <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--userinfo部分-->
      <%= render 'users/userinfo', user: current_user %>
      <!--新規投稿フォーム-->
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <!--userの一覧部分-->
      <%= render 'index', users: @users %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <!--userinfo部分-->
      <%= render 'userinfo', user: @user %>
      <% if current_user != @user %>
        <% if current_user.following?(@user) %>
          <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: 'btn btn-info' %>
        <% else %>
          <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: 'btn btn-success' %>
        <% end %>
      <% end %>
      <!--新規投稿フォーム-->
      <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <!--本の一覧部分-->
      <%= render 'books/index', books: @user.books %>
    </div>
  </div>
</div>